name: "GitHub Repository Configuration"

dependabot:
  version: 2
  updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
        interval: "weekly"

repository:
  default_branch: "main"
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

notes:
  source: "Joplin"
  sync_schedule: "daily"
